baseURL = 'https://ig-fahrrad.at'
# baseURL is set on command line when building
#relativeURLs = true
languageCode = 'en-us'
title = 'IHR FAHRRADGESCHÄFT IN WIEN'
theme = "ananke"

# set to production when google should index it
environment = "production"
minify = true

[params]
  description = "Promoting cycling in the city."
  author = "IG Fahrrad"

[markup.goldmark.renderer]
  unsafe = true

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 3

