name: build
on:
  push:
    branches: [ unused ]

  workflow_dispatch:
    inputs:
      debug:
        description: enable tmate console debugging     
        required: false
        default: "disabled"

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.112.7"
          extended: true

      - uses: actions/cache@v3
        with:
          path: /tmp/hugo_cache
          key: ${{ runner.os }}-hugomod-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-hugomod-

      ##- name: install nodejs
      ##  uses: actions/setup-node@v3
      ##  with:
      ##    node-version: '18'

      ##- name: install-node_modules
      ##  run: |
      ##    npm install
      ##    cp ./node_modules/bulma/css/bulma.css ./node_modules/font-awesome/css/font-awesome.css
      ##  working-directory: blog      

      - name: Build
        run: |
          echo "Build for gh-pages..."
          echo "# Trading the Trades Website " >> $GITHUB_STEP_SUMMARY
          echo "## Build Report " >> $GITHUB_STEP_SUMMARY
          echo "- Github Pages" >> $GITHUB_STEP_SUMMARY
          hugo --minify
          echo "- aberger.at " >> $GITHUB_STEP_SUMMARY
          hugo --minify --destination trading --baseURL=https://tradingthetrades.com
          zip -r igfahrrad.zip igfahrrad
          mkdir -p public/download
          mv igfahrrad.zip public/download
        working-directory: igfahrrad

      - uses: actions/upload-artifact@master
        with:
          name: page
          path: blog/public
          if-no-files-found: error

  deploy-gh-pages: # do not rename this, webhook listens to exactly this workflow name
    runs-on: ubuntu-22.04
    needs: build
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    permissions:
      contents: read
      pages: write
      id-token: write      
    steps:
    - uses: actions/download-artifact@v3
      with:
        name: page
        path: .

    - name: show artifacts
      run: |
        pwd
        ls -l

    - uses: actions/configure-pages@v3

    - uses: actions/upload-pages-artifact@v1.0.8
      with:
        path: .
    - id: deployment
      uses: actions/deploy-pages@main

    - name: summary-report
      run: |
        echo "## Deployment " >> $GITHUB_STEP_SUMMARY
        echo "visit [Github Pages](https://qrzbrz.github.io/flo-blog/) now" >> $GITHUB_STEP_SUMMARY
        echo "after some minutes the site should be available at [https://tradingthetrades.com](https://tradingthetrades.com) " >> $GITHUB_STEP_SUMMARY
