name: build
on:
  push:
    branches: [ main ]

jobs:
  build:
    uses: ./.github/workflows/hugo.yaml
    with:
      baseUrl: https://tradingthetrades.com
          
  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - uses: actions/checkout@v3

      - uses: actions/download-artifact@v3
        with:
          name: page
          path: public

      - run: |
          touch .gcloudignore
          touch ./public/.gcloudignore
          pwd
          ls -l

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: 'projects/26148234804/locations/global/workloadIdentityPools/gh-cicd-pool/providers/gh-provider'
          service_account: 'ghaction-service-account@tradingthetrades.iam.gserviceaccount.com'

      - id: 'upload-folder'
        uses: 'google-github-actions/upload-cloud-storage@v1'
        with:
          path: 'public'
          destination: 'www-trading'
          parent: false